name: Sharding
version: 1.0.0

config_files:
  - path: /workspaces/config/sharding

config:
  concept_step: Concept

  codes_metadata: # extract code order
    - path: /workspaces/WeavEHR.example/output/project/datasets/extraction/metadata/codes.parquet

  datasets:
    include: 
      # - mimic-demo
      - mimic-iv

  concepts:
    include_all: true

  subjects:
    include_all: true